import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "jsr:@supabase/supabase-js@2/cors";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const clean=(v:any)=>String(v??"").trim()||null;
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});let createdStudent:string|null=null,createdParentIds:string[]=[];try{
const auth=req.headers.get("Authorization");if(!auth)return json({error:"Authentification requise."},401);const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return json({error:"Configuration Supabase serveur incomplète."},500);
const caller=createClient(url,anon,{global:{headers:{Authorization:auth}}});const token=auth.replace(/^Bearer\s+/i,"");const {data:au,error:ae}=await caller.auth.getUser(token);if(ae||!au.user)return json({error:"Session invalide."},401);
const db=createClient(url,service);const {data:profile,error:pe}=await db.from("profiles").select("school_id,active,roles(name)").eq("id",au.user.id).maybeSingle();if(pe||!profile?.active||!profile.school_id)return json({error:"Aucun accès scolaire actif."},403);const role=(profile.roles as any)?.name;if(!["promoteur","directeur","secretaire"].includes(role))return json({error:"Vous n'avez pas le droit d'inscrire un enfant."},403);
const body=await req.json(),schoolId=String(profile.school_id),student=body.student||{},parent1=body.parent1||{},parent2=body.parent2||{},classId=clean(body.class_id),yearId=clean(body.academic_year_id);if(!student.last_name||!student.first_name||!classId||!yearId||!parent1.last_name||!parent1.first_name||!parent1.phone)return json({error:"Nom/prénom de l'enfant, classe, année scolaire et informations du parent principal sont obligatoires."},400);const [{data:classRow},{data:yearRow}]=await Promise.all([db.from("classes").select("id").eq("id",classId).eq("school_id",schoolId).maybeSingle(),db.from("academic_years").select("id").eq("id",yearId).eq("school_id",schoolId).maybeSingle()]);if(!classRow)return json({error:"La classe sélectionnée n'appartient pas à cet établissement."},400);if(!yearRow)return json({error:"L'année scolaire sélectionnée n'appartient pas à cet établissement."},400);
const matricule=clean(student.matricule)||("SV-"+new Date().getFullYear()+"-"+crypto.randomUUID().slice(0,5).toUpperCase()),registrationNumber=clean(body.registration_number)||("INS-"+new Date().getFullYear()+"-"+crypto.randomUUID().slice(0,5).toUpperCase()),accessCode="P-"+crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase();
const {data:studentRow,error:se}=await db.from("students").insert({school_id:schoolId,matricule,last_name:String(student.last_name).trim(),first_name:String(student.first_name).trim(),post_name:clean(student.post_name),sex:clean(student.sex)||"M",date_of_birth:clean(student.date_of_birth),place_of_birth:clean(student.place_of_birth),address:clean(student.address),phone:clean(student.phone),email:clean(student.email),photo_url:clean(student.photo_url),photo_path:clean(student.photo_path),active:true,parent_access_code:accessCode}).select("id,matricule,parent_access_code").single();if(se)return json({error:"Impossible d'enregistrer l'élève: "+se.message},400);createdStudent=studentRow.id;
const parents=[parent1,parent2].filter((p:any)=>p.last_name&&p.first_name);for(let i=0;i<parents.length;i++){const p=parents[i];const {data:pr,error:pre}=await db.from("parents").insert({school_id:schoolId,last_name:String(p.last_name).trim(),first_name:String(p.first_name).trim(),phone:clean(p.phone),email:clean(p.email),address:clean(p.address),occupation:clean(p.occupation)}).select("id").single();if(pre||!pr)throw new Error("Enregistrement du parent impossible: "+(pre?.message||"réponse vide"));createdParentIds.push(pr.id);const {error:spe}=await db.from("student_parents").insert({student_id:studentRow.id,parent_id:pr.id,relationship:clean(p.relationship)||"Père/Mère",is_primary:i===0});if(spe)throw new Error("Rattachement du parent impossible: "+spe.message);}
const {data:enroll,error:ee}=await db.from("enrollments").insert({school_id:schoolId,student_id:studentRow.id,class_id:classId,academic_year_id:yearId,registration_number:registrationNumber,status:"active"}).select("id,registration_number").single();if(ee)throw new Error("Inscription scolaire impossible: "+ee.message);
return json({success:true,student:{id:studentRow.id,matricule:studentRow.matricule,parent_access_code:studentRow.parent_access_code},enrollment:enroll});
}catch(e){if(createdStudent){try{const url=Deno.env.get("SUPABASE_URL")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",db=createClient(url,service);await db.from("student_parents").delete().eq("student_id",createdStudent);if(createdParentIds.length)await db.from("parents").delete().in("id",createdParentIds);await db.from("enrollments").delete().eq("student_id",createdStudent);await db.from("students").delete().eq("id",createdStudent)}catch{}}return json({error:e instanceof Error?e.message:"Erreur serveur."},500)}});
