"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
import {LayoutDashboard,Users,GraduationCap,Wallet,Settings,LogOut,Menu,X,Search,Plus,Printer,ShieldCheck,BookOpen,UserCog,Receipt,UserRound,School,Save} from "lucide-react";

type P={id:string;school_id:string;full_name:string|null;role_id:string|null;active:boolean;roles?:{name:string;label:string}|null};
const money=(n:number)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(n)+" FC";
const today=()=>new Date().toISOString().slice(0,10);

export default function Home(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<P|null>(null),[school,setSchool]=useState<any>(null),[page,setPage]=useState("dashboard"),[loading,setLoading]=useState(true),[mobile,setMobile]=useState(false),[error,setError]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(typeof window!=="undefined"&&window.location.hash&&(window.location.hash.includes("type=recovery")||window.location.hash.includes("access_token="))){window.location.replace("/platform/reset-password"+window.location.hash);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadUser(data.session.user.id);else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadUser(s.user.id);else{setProfile(null);setLoading(false)}});return()=>subscription.unsubscribe()},[]);
 async function loadUser(uid:string){setLoading(true);setError("");const {data:p,error:e}=await supabase.from("profiles").select("*,roles(name,label)").eq("id",uid).maybeSingle();if(e)setError(e.message);if(p?.active){setProfile(p);await loadSchool(p.school_id)}else{setProfile(null);setError("Votre compte est authentifié, mais aucun accès à un établissement ne lui est encore attribué. Le Super Administrateur doit d'abord créer l'école puis vous affecter un rôle.");}setLoading(false)}
 async function loadSchool(id:string){const {data}=await supabase.from("schools").select("*").eq("id",id).single();setSchool(data)}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 async function logout(){await supabase.auth.signOut()}
 if(loading)return <div className="center"><div className="loader"/><p>Chargement de Saint Victor…</p></div>;
 if(!session)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} busy={busy} error={error} onSubmit={login}/>;
 if(!profile)return <div className="center"><ShieldCheck size={42}/><h2>Compte en attente</h2><p>{error||"Compte authentifié sans profil scolaire actif."}</p><button className="btn" onClick={logout}>Se déconnecter</button></div>;
 const role=profile.roles?.name||"promoteur";
 const can=(...r:string[])=>r.includes(role);
 const nav:any[]=[
  ["dashboard","Tableau de bord",LayoutDashboard,true],
  ["students","Élèves",Users,true],
  ["studies","Études",GraduationCap,can("promoteur","directeur","administrateur","etudes","enseignant","surveillant")],
  ["finance","Finances",Wallet,can("promoteur","directeur","administrateur","finance","comptable")],
  ["staff","Personnel",UserCog,can("promoteur","directeur","administrateur")],
  ["settings","Paramètres",Settings,can("promoteur","directeur","administrateur")]
 ];
 return <div className="app"><aside className={mobile?"side open":"side"}><div className="brand"><div className="logo">{school?.logo_url?<img src={school.logo_url} alt=""/>:"SV"}</div><div><b>{school?.name||"COMPLEXE SCOLAIRE SAINT VICTOR"}</b><small>Savoir • Discipline • Réussite</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.filter(n=>n[3]).map(n=>{const I=n[2];return <button key={n[0]} className={page===n[0]?"navActive":""} onClick={()=>{setPage(n[0]);setMobile(false)}}><I size={19}/>{n[1]}</button>})}<a className="platformLink" href="/platform/login"><ShieldCheck size={19}/> Administration plateforme</a></nav><div className="sideBottom"><span>{profile.full_name||session.user.email}</span><small>{profile.roles?.label||role}</small><button className="logout" onClick={logout}><LogOut size={17}/> Déconnexion</button></div></aside><main className="main"><header className="top"><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="searchBox"><Search size={18}/><input placeholder="Rechercher dans l’établissement…"/></div><div className="topUser">{profile.roles?.label||role}</div></header><section className="content">{page==="dashboard"&&<Dashboard profile={profile} school={school}/>} {page==="students"&&<Students profile={profile} can={can}/>} {page==="studies"&&<Studies profile={profile} can={can}/>} {page==="finance"&&<Finance profile={profile} can={can}/>} {page==="staff"&&<Staff profile={profile}/>} {page==="settings"&&<SettingsPage school={school} profile={profile} reload={()=>loadSchool(profile.school_id)}/>}</section></main></div>;
}

function Login({email,password,setEmail,setPassword,busy,error,onSubmit}:any){return <div className="login"><div className="loginCard"><div className="logo big">SV</div><h1>COMPLEXE SCOLAIRE<br/>SAINT VICTOR</h1><p>Plateforme de gestion scolaire</p><form onSubmit={onSubmit}><label>Email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="administration@ecole.cd"/></label><label>Mot de passe<input type="password" required value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="btn full" disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form><a href="/platform/login" className="platformAccess">🔐 Connexion Super Administrateur</a><small>Accès sécurisé par Supabase Auth</small></div></div>}

function Stat({title,value,icon}:any){return <div className="stat"><div className="icon">{icon}</div><small>{title}</small><b>{value}</b></div>}

function Dashboard({profile,school}:any){
 const [c,setC]=useState({students:0,teachers:0,classes:0,payments:0,expenses:0});
 useEffect(()=>{(async()=>{const id=profile.school_id;const [s,t,k,p,e]=await Promise.all([supabase.from("students").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("teachers").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("classes").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("payments").select("amount").eq("school_id",id).eq("status","validated"),supabase.from("expenses").select("amount").eq("school_id",id).eq("status","validated")]);setC({students:s.count||0,teachers:t.count||0,classes:k.count||0,payments:(p.data||[]).reduce((a:any,x:any)=>a+Number(x.amount||0),0),expenses:(e.data||[]).reduce((a:any,x:any)=>a+Number(x.amount||0),0)})})()},[profile.school_id]);
 return <><div className="head"><div><h1>Tableau de bord</h1><p>{school?.name} • Année scolaire 2026–2027</p></div></div><div className="cards"><Stat title="Élèves" value={c.students} icon={<Users/>}/><Stat title="Enseignants" value={c.teachers} icon={<UserCog/>}/><Stat title="Classes" value={c.classes} icon={<BookOpen/>}/><Stat title="Encaissements" value={money(c.payments)} icon={<Wallet/>}/></div><div className="twoCols"><div className="panel"><h3>Situation financière</h3><div className="financeSummary"><div><small>Encaissements</small><b>{money(c.payments)}</b></div><div><small>Dépenses</small><b>{money(c.expenses)}</b></div><div><small>Solde</small><b>{money(c.payments-c.expenses)}</b></div></div></div><div className="panel"><h3>Accès</h3><p><b>{profile.full_name||"Utilisateur"}</b><br/><span className="role">{profile.roles?.label}</span></p><span className="badge">Compte actif</span></div></div></>
}

function Students({profile,can}:any){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[show,setShow]=useState(false),[form,setForm]=useState<any>({first_name:"",last_name:"",post_name:"",sex:"M",date_of_birth:"",phone:"",address:"",email:""}),[msg,setMsg]=useState("");
 async function load(){const {data}=await supabase.from("students").select("*").eq("school_id",profile.school_id).order("last_name");setRows(data||[])}
 useEffect(()=>{load()},[profile.school_id]);
 const filtered=useMemo(()=>rows.filter(x=>(x.matricule+" "+x.first_name+" "+x.last_name+" "+(x.phone||"")).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function save(e:React.FormEvent){e.preventDefault();setMsg("");const matricule="SV-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-5);const {error}=await supabase.from("students").insert({school_id:profile.school_id,matricule,...form,active:true});if(error)setMsg(error.message);else{setForm({first_name:"",last_name:"",post_name:"",sex:"M",date_of_birth:"",phone:"",address:"",email:""});setShow(false);load()}}
 return <><div className="head"><div><h1>Élèves</h1><p>Inscription, matricule, dossier et impression des listes/cartes.</p></div>{can("promoteur","directeur","administrateur","secretaire")&&<button className="btn" onClick={()=>setShow(!show)}><Plus size={17}/> Nouvel élève</button>}</div>{show&&<form className="panel formGrid" onSubmit={save}><label>Nom<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Prénom<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Postnom<input value={form.post_name} onChange={e=>setForm({...form,post_name:e.target.value})}/></label><label>Sexe<select value={form.sex} onChange={e=>setForm({...form,sex:e.target.value})}><option>M</option><option>F</option></select></label><label>Date de naissance<input type="date" value={form.date_of_birth} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Adresse<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{msg&&<div className="error">{msg}</div>}<button className="btn"><Save size={16}/> Enregistrer l’élève</button></form>}<div className="panel"><div className="toolbar"><div className="miniSearch"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nom, prénom, matricule, téléphone…"/></div><button className="btn light" onClick={()=>window.print()}><Printer size={17}/> Imprimer</button></div><div className="tableWrap"><table><thead><tr><th>Matricule</th><th>Élève</th><th>Sexe</th><th>Téléphone</th><th>Statut</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><b>{s.matricule}</b></td><td>{s.last_name} {s.first_name} {s.post_name||""}</td><td>{s.sex||"—"}</td><td>{s.phone||"—"}</td><td><span className="badge">{s.active?"Actif":"Inactif"}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={5} className="empty">Aucun élève enregistré.</td></tr>}</tbody></table></div></div></>
}

function Studies({profile,can}:any){
 const [tab,setTab]=useState("classes"),[classes,setClasses]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>({name:"",room:"",capacity:"",first_name:"",last_name:"",phone:"",subject:"",code:"",coefficient:"1"}),[msg,setMsg]=useState("");
 async function load(){const [a,b,c]=await Promise.all([supabase.from("classes").select("*").eq("school_id",profile.school_id).order("name"),supabase.from("teachers").select("*").eq("school_id",profile.school_id).order("last_name"),supabase.from("subjects").select("*").eq("school_id",profile.school_id).order("name")]);setClasses(a.data||[]);setTeachers(b.data||[]);setSubjects(c.data||[])}
 useEffect(()=>{load()},[profile.school_id]);
 async function save(e:React.FormEvent){e.preventDefault();setMsg("");let table="classes",data:any={school_id:profile.school_id,name:form.name,room:form.room||null,capacity:form.capacity?Number(form.capacity):null};if(tab==="teachers"){table="teachers";data={school_id:profile.school_id,matricule:"ENS-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-5),first_name:form.first_name,last_name:form.last_name,phone:form.phone||null,subject:form.subject||null,active:true}}if(tab==="subjects"){table="subjects";data={school_id:profile.school_id,name:form.name,code:form.code||null,coefficient:Number(form.coefficient||1)}}const {error}=await supabase.from(table).insert(data);if(error)setMsg(error.message);else{setShow(false);setForm({name:"",room:"",capacity:"",first_name:"",last_name:"",phone:"",subject:"",code:"",coefficient:"1"});load()}}
 return <><div className="head"><div><h1>Études</h1><p>Classes, enseignants et matières.</p></div>{can("promoteur","directeur","administrateur","etudes")&&<button className="btn" onClick={()=>setShow(!show)}><Plus size={17}/> Ajouter</button>}</div><div className="tabs">{[["classes","Classes"],["teachers","Enseignants"],["subjects","Matières"]].map(x=><button className={tab===x[0]?"tab active":"tab"} key={x[0]} onClick={()=>{setTab(x[0]);setShow(false)}}>{x[1]}</button>)}</div>{show&&<form className="panel formGrid" onSubmit={save}>{tab==="teachers"?<><label>Nom<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Prénom<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Matière<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label></>:tab==="subjects"?<><label>Matière<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Coefficient<input type="number" step="0.5" value={form.coefficient} onChange={e=>setForm({...form,coefficient:e.target.value})}/></label></>:<><label>Nom de la classe<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Salle<input value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/></label><label>Capacité<input type="number" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label></>}{msg&&<div className="error">{msg}</div>}<button className="btn"><Save size={16}/> Enregistrer</button></form>}<div className="panel"><div className="tableWrap">{tab==="classes"?<table><thead><tr><th>Classe</th><th>Salle</th><th>Capacité</th></tr></thead><tbody>{classes.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.room||"—"}</td><td>{x.capacity||"—"}</td></tr>)}</tbody></table>:tab==="teachers"?<table><thead><tr><th>Matricule</th><th>Enseignant</th><th>Matière</th><th>Téléphone</th></tr></thead><tbody>{teachers.map(x=><tr key={x.id}><td>{x.matricule}</td><td>{x.last_name} {x.first_name}</td><td>{x.subject||"—"}</td><td>{x.phone||"—"}</td></tr>)}</tbody></table>:<table><thead><tr><th>Code</th><th>Matière</th><th>Coefficient</th></tr></thead><tbody>{subjects.map(x=><tr key={x.id}><td>{x.code||"—"}</td><td>{x.name}</td><td>{x.coefficient}</td></tr>)}</tbody></table>}{((tab==="classes"&&!classes.length)||(tab==="teachers"&&!teachers.length)||(tab==="subjects"&&!subjects.length))&&<p className="empty">Aucune donnée enregistrée.</p>}</div></div></>
}

function Finance({profile,can}:any){
 const [tab,setTab]=useState("payments"),[payments,setPayments]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>({student_id:"",amount:"",method:"cash",reference:"",category:"Fonctionnement",description:""}),[msg,setMsg]=useState("");
 async function load(){const [p,e,s]=await Promise.all([supabase.from("payments").select("*").eq("school_id",profile.school_id).order("paid_at",{ascending:false}),supabase.from("expenses").select("*").eq("school_id",profile.school_id).order("paid_at",{ascending:false}),supabase.from("students").select("id,matricule,last_name,first_name").eq("school_id",profile.school_id).order("last_name")]);setPayments(p.data||[]);setExpenses(e.data||[]);setStudents(s.data||[])}
 useEffect(()=>{load()},[profile.school_id]);
 const income=payments.reduce((a,x)=>a+Number(x.amount||0),0),out=expenses.reduce((a,x)=>a+Number(x.amount||0),0);
 async function save(e:React.FormEvent){e.preventDefault();setMsg("");let data:any;let table=tab==="payments"?"payments":"expenses";if(table==="payments"){data={school_id:profile.school_id,student_id:form.student_id,receipt_number:"REC-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-6),amount:Number(form.amount),method:form.method,reference:form.reference||null,status:"validated",received_by:profile.id,note:null}}else data={school_id:profile.school_id,category:form.category,description:form.description,amount:Number(form.amount),status:"validated",created_by:profile.id};const {error}=await supabase.from(table).insert(data);if(error)setMsg(error.message);else{setShow(false);setForm({student_id:"",amount:"",method:"cash",reference:"",category:"Fonctionnement",description:""});load()}}
 return <><div className="head"><div><h1>Finances</h1><p>Encaissements, reçus, dépenses et solde.</p></div>{can("promoteur","directeur","administrateur","finance","comptable")&&<button className="btn" onClick={()=>setShow(!show)}><Plus size={17}/> {tab==="payments"?"Nouvel encaissement":"Nouvelle dépense"}</button>}</div><div className="cards"><Stat title="Encaissements" value={money(income)} icon={<Receipt/>}/><Stat title="Dépenses" value={money(out)} icon={<Wallet/>}/><Stat title="Solde" value={money(income-out)} icon={<Wallet/>}/><Stat title="Transactions" value={payments.length+expenses.length} icon={<BookOpen/>}/></div><div className="tabs"><button className={tab==="payments"?"tab active":"tab"} onClick={()=>{setTab("payments");setShow(false)}}>Encaissements</button><button className={tab==="expenses"?"tab active":"tab"} onClick={()=>{setTab("expenses");setShow(false)}}>Dépenses</button></div>{show&&<form className="panel formGrid" onSubmit={save}>{tab==="payments"?<><label>Élève<select required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Choisir…</option>{students.map(s=><option key={s.id} value={s.id}>{s.matricule} — {s.last_name} {s.first_name}</option>)}</select></label><label>Montant<input type="number" min="1" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Mode<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="cash">Espèces</option><option value="mobile_money">Mobile Money</option><option value="bank">Banque</option></select></label><label>Référence<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label></>:<><label>Catégorie<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Montant<input type="number" min="1" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}{msg&&<div className="error">{msg}</div>}<button className="btn"><Save size={16}/> Enregistrer</button></form>}<div className="panel tableWrap"><table><thead><tr><th>Date</th><th>{tab==="payments"?"Reçu":"Catégorie"}</th><th>Description</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{(tab==="payments"?payments:expenses).map(x=><tr key={x.id}><td>{new Date(x.paid_at||Date.now()).toLocaleDateString("fr-FR")}</td><td>{x.receipt_number||x.category}</td><td>{x.description||x.method}</td><td><b>{money(Number(x.amount))}</b></td><td><span className="badge">{x.status}</span></td></tr>)}</tbody></table>{!(tab==="payments"?payments:expenses).length&&<p className="empty">Aucune transaction.</p>}</div></>
}

function Staff({profile}:any){
 const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from("profiles").select("id,full_name,phone,active,roles(label)").eq("school_id",profile.school_id).then(({data})=>setRows(data||[]))},[profile.school_id]);
 return <><div className="head"><div><h1>Personnel & accès</h1><p>Comptes rattachés à l’établissement et rôles applicatifs.</p></div></div><div className="panel"><div className="tableWrap"><table><thead><tr><th>Nom</th><th>Téléphone</th><th>Rôle</th><th>Statut</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.full_name||"—"}</td><td>{x.phone||"—"}</td><td>{x.roles?.label||"—"}</td><td><span className="badge">{x.active?"Actif":"Inactif"}</span></td></tr>)}</tbody></table></div><p className="notice">La création des comptes utilisateurs doit passer par l’invitation sécurisée Supabase ; aucun mot de passe n’est stocké dans l’application.</p></div></>
}

function SettingsPage({school,profile,reload}:any){
 const [form,setForm]=useState<any>({name:school?.name||"",logo_url:school?.logo_url||"",primary_color:school?.primary_color||"#0f3d5e",secondary_color:school?.secondary_color||"#d4af37",phone:school?.phone||"",email:school?.email||"",address:school?.address||"",city:school?.city||"Kinshasa",currency:school?.currency||"USD"}),[msg,setMsg]=useState("");
 useEffect(()=>{setForm({name:school?.name||"",logo_url:school?.logo_url||"",primary_color:school?.primary_color||"#0f3d5e",secondary_color:school?.secondary_color||"#d4af37",phone:school?.phone||"",email:school?.email||"",address:school?.address||"",city:school?.city||"Kinshasa",currency:school?.currency||"USD"})},[school]);
 async function save(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from("schools").update({...form,updated_at:new Date().toISOString()}).eq("id",profile.school_id);setMsg(error?error.message:"Paramètres enregistrés.");if(!error)reload()}
 return <><div className="head"><div><h1>Paramètres</h1><p>Personnalisez l’identité de votre établissement sans modifier le code.</p></div></div><form className="panel formGrid" onSubmit={save}><label>Nom de l’école<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Logo URL<input value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})} placeholder="https://…"/></label><label>Couleur principale<input type="color" value={form.primary_color} onChange={e=>setForm({...form,primary_color:e.target.value})}/></label><label>Couleur secondaire<input type="color" value={form.secondary_color} onChange={e=>setForm({...form,secondary_color:e.target.value})}/></label><label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Adresse<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Ville<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Devise<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option><option>FC</option></select></label>{msg&&<div className={msg.includes("enregistr")?"notice":"error"}>{msg}</div>}<button className="btn"><Save size={16}/> Enregistrer les paramètres</button></form></>
}
