"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
import {LayoutDashboard,Users,GraduationCap,Wallet,Settings,LogOut,Menu,X,Search,Plus,Printer,ShieldCheck,BookOpen,UserCog} from "lucide-react";

type Profile={id:string;school_id:string;full_name:string|null;role_id:string|null;active:boolean;roles?:{name:string;label:string}|null};
type Student={id:string;matricule:string;last_name:string;first_name:string;post_name:string|null;sex:string|null;phone:string|null;active:boolean};
type Teacher={id:string;matricule:string;last_name:string;first_name:string;subject:string|null;phone:string|null;active:boolean};
const money=(n:number)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(n)+" FC";

export default function Home(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[school,setSchool]=useState<any>(null),[page,setPage]=useState("dashboard"),[loading,setLoading]=useState(true),[mobile,setMobile]=useState(false),[error,setError]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadUser(data.session.user.id);else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadUser(s.user.id);else{setProfile(null);setLoading(false)}});return()=>subscription.unsubscribe()},[]);
 async function loadUser(uid:string){setLoading(true);const {data:p}=await supabase.from("profiles").select("*, roles(name,label)").eq("id",uid).maybeSingle();if(!p){const {data:s}=await supabase.from("schools").select("id").limit(1).single();const {data:r}=await supabase.from("roles").select("id").eq("name","promoteur").single();if(s&&r){const {data:n,error:e}=await supabase.from("profiles").insert({id:uid,school_id:s.id,role_id:r.id,full_name:"Promoteur",active:true}).select("*, roles(name,label)").single();if(e)setError(e.message);else{setProfile(n);await loadSchool(s.id)}}}else{setProfile(p);await loadSchool(p.school_id)}setLoading(false)}
 async function loadSchool(id:string){const {data}=await supabase.from("schools").select("*").eq("id",id).single();setSchool(data)}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const {error:e2}=await supabase.auth.signInWithPassword({email,password});if(e2)setError(e2.message);setBusy(false)}
 async function logout(){await supabase.auth.signOut()}
 if(loading)return <div className="center"><div className="loader"/><p>Chargement de Saint Victor…</p></div>;
 if(!session)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} busy={busy} error={error} onSubmit={login}/>;
 if(!profile)return <div className="center"><ShieldCheck size={42}/><h2>Compte en attente</h2><p>{error||"Compte authentifié sans profil scolaire actif."}</p><button className="btn" onClick={logout}>Se déconnecter</button></div>;
 const role=profile.roles?.name||"promoteur",can=(...r:string[])=>r.includes(role);
 const nav:any[]=[["dashboard","Tableau de bord",LayoutDashboard,true],["students","Élèves",Users,true],["studies","Études",GraduationCap,can("promoteur","directeur","administrateur","etudes","enseignant","surveillant")],["finance","Finances",Wallet,can("promoteur","directeur","administrateur","finance","comptable")],["staff","Personnel",UserCog,can("promoteur","directeur","administrateur","etudes")],["settings","Paramètres",Settings,can("promoteur","directeur","administrateur")]];
 return <div className="app"><aside className={mobile?"side open":"side"}><div className="brand"><div className="logo">SV</div><div><b>{school?.name||"COMPLEXE SCOLAIRE SAINT VICTOR"}</b><small>Savoir • Discipline • Réussite</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.filter(n=>n[3]).map(n=>{const I=n[2];return <button key={n[0]} className={page===n[0]?"navActive":""} onClick={()=>{setPage(n[0]);setMobile(false)}}><I size={19}/>{n[1]}</button>})}<a className="platformLink" href="/platform/login"><ShieldCheck size={19}/> Administration plateforme</a></nav><div className="sideBottom"><span>{profile.full_name||session.user.email}</span><small>{profile.roles?.label||role}</small><button className="logout" onClick={logout}><LogOut size={17}/> Déconnexion</button></div></aside><main className="main"><header className="top"><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="searchBox"><Search size={18}/><input placeholder="Rechercher un élève, matricule, classe…"/></div><div className="topUser">{profile.roles?.label||role}</div></header><section className="content">{page==="dashboard"&&<Dashboard profile={profile} school={school}/>} {page==="students"&&<Students profile={profile} can={can}/>} {page==="studies"&&<Studies profile={profile} can={can}/>} {page==="finance"&&<Finance profile={profile}/>} {page==="staff"&&<Staff profile={profile}/>} {page==="settings"&&<SettingsPage school={school} profile={profile} reload={()=>loadSchool(profile.school_id)}/>}</section></main></div>;
}

function Login({email,password,setEmail,setPassword,busy,error,onSubmit}:any){
 const [signup,setSignup]=useState(false),[msg,setMsg]=useState("");
 async function createAccount(){
   if(!email||password.length<8){setMsg("Entrez un email et un mot de passe d'au moins 8 caractères.");return}
   const {data,error:e}=await supabase.auth.signUp({email,password});
   if(e){setMsg(e.message);return}
   if(data.session)setMsg("Compte créé. Chargement…");else setMsg("Compte créé. Vérifiez votre email si nécessaire, puis connectez-vous.");
 }
 return <div className="login"><div className="loginCard"><div className="logo big">SV</div><h1>COMPLEXE SCOLAIRE<br/>SAINT VICTOR</h1><p>Plateforme de gestion scolaire</p><form onSubmit={onSubmit}><label>Email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="administration@ecole.cd"/></label><label>Mot de passe<input type="password" required value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error&&<div className="error">{error}</div>}{msg&&<div className="notice">{msg}</div>}<button className="btn full" disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form><button className="btn light full" onClick={async()=>{setSignup(true);await createAccount()}}>Première connexion / créer le compte</button>{signup&&<p className="muted">Le premier compte devient automatiquement le <b>Promoteur</b>. Les comptes suivants devront être attribués par la direction.</p>}<a href="/platform/login" className="platformAccess">🔐 Connexion Super Administrateur de la plateforme</a><small>Accès sécurisé par Supabase Auth</small></div></div>
}

function Stat({title,value,icon}:any){return <div className="stat"><div className="icon">{icon}</div><small>{title}</small><b>{value}</b></div>}

function Dashboard({profile,school}:any){
 const [c,setC]=useState({students:0,teachers:0,classes:0,total:0});
 useEffect(()=>{(async()=>{const id=profile.school_id;const [s,t,k,p]=await Promise.all([supabase.from("students").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("teachers").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("classes").select("*",{count:"exact",head:true}).eq("school_id",id),supabase.from("payments").select("amount").eq("school_id",id).eq("status","validated")]);setC({students:s.count||0,teachers:t.count||0,classes:k.count||0,total:(p.data||[]).reduce((a:any,x:any)=>a+Number(x.amount||0),0)})})()},[profile.school_id]);
 return <><div className="head"><div><h1>Tableau de bord</h1><p>Bienvenue dans <b>{school?.name}</b> • Année scolaire 2026–2027</p></div></div><div className="cards"><Stat title="Élèves inscrits" value={c.students} icon={<Users/>}/><Stat title="Enseignants" value={c.teachers} icon={<UserCog/>}/><Stat title="Classes" value={c.classes} icon={<BookOpen/>}/><Stat title="Encaissements" value={money(c.total)} icon={<Wallet/>}/></div><div className="twoCols"><div className="panel"><h3>Modules principaux</h3><div className="quick"><span><Users/> Gestion des élèves</span><span><GraduationCap/> Études & résultats</span><span><Wallet/> Finance & reçus</span><span><ShieldCheck/> Accès par rôle</span></div></div><div className="panel"><h3>Compte connecté</h3><p><b>{profile.full_name||"Utilisateur"}</b><br/><span className="role">{profile.roles?.label}</span></p><span className="badge">Compte actif</span></div></div></>
}

function Students({profile,can}:any){
 const [rows,setRows]=useState<Student[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data}=await supabase.from("students").select("*").eq("school_id",profile.school_id).order("last_name");setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[profile.school_id]);
 const filtered=useMemo(()=>rows.filter(x=>(x.matricule+" "+x.first_name+" "+x.last_name+" "+(x.phone||"")).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function add(){const first=prompt("Prénom");if(!first)return;const last=prompt("Nom");if(!last)return;const {error}=await supabase.from("students").insert({school_id:profile.school_id,matricule:"SV-"+Date.now().toString().slice(-6),first_name:first,last_name:last,active:true});if(error)alert(error.message);else load()}
 return <><div className="head"><div><h1>Élèves</h1><p>Inscriptions, matricules, dossiers et cartes.</p></div>{can("promoteur","directeur","administrateur","secretaire")&&<button className="btn" onClick={add}><Plus size={17}/> Nouvel élève</button>}</div><div className="panel"><div className="toolbar"><div className="miniSearch"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher…"/></div><button className="btn light" onClick={()=>window.print()}><Printer size={17}/> Imprimer</button></div>{loading?<p>Chargement…</p>:<div className="tableWrap"><table><thead><tr><th>Matricule</th><th>Élève</th><th>Sexe</th><th>Téléphone</th><th>Statut</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><b>{s.matricule}</b></td><td>{s.last_name} {s.first_name} {s.post_name||""}</td><td>{s.sex||"—"}</td><td>{s.phone||"—"}</td><td><span className="badge">{s.active?"Actif":"Inactif"}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={5} className="empty">Aucun élève enregistré.</td></tr>}</tbody></table></div>}</div></>
}

function Studies({profile,can}:any){
 const [teachers,setTeachers]=useState<Teacher[]>([]),[classes,setClasses]=useState<any[]>([]);
 async function load(){const [t,k]=await Promise.all([supabase.from("teachers").select("*").eq("school_id",profile.school_id).order("last_name"),supabase.from("classes").select("*").eq("school_id",profile.school_id).order("name")]);setTeachers(t.data||[]);setClasses(k.data||[])}
 useEffect(()=>{load()},[profile.school_id]);
 async function addTeacher(){const first=prompt("Prénom");if(!first)return;const last=prompt("Nom");if(!last)return;const subject=prompt("Matière","");const {error}=await supabase.from("teachers").insert({school_id:profile.school_id,matricule:"ENS-"+Date.now().toString().slice(-6),first_name:first,last_name:last,subject,active:true});if(error)alert(error.message);else load()}
 return <><div className="head"><div><h1>Études</h1><p>Classes, enseignants, matières, affectations, présences et résultats.</p></div>{can("promoteur","directeur","administrateur","etudes")&&<button className="btn" onClick={addTeacher}><Plus size={17}/> Nouvel enseignant</button>}</div><div className="cards"><Stat title="Classes" value={classes.length} icon={<BookOpen/>}/><Stat title="Enseignants" value={teachers.length} icon={<UserCog/>}/><Stat title="Matières" value="—" icon={<GraduationCap/>}/><Stat title="Bulletins" value="—" icon={<ShieldCheck/>}/></div><div className="twoCols"><div className="panel"><h3>Classes</h3>{classes.length?<table><thead><tr><th>Classe</th><th>Salle</th><th>Capacité</th></tr></thead><tbody>{classes.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.room||"—"}</td><td>{c.capacity||"—"}</td></tr>)}</tbody></table>:<p className="empty">Aucune classe configurée.</p>}</div><div className="panel"><h3>Enseignants</h3>{teachers.length?<table><thead><tr><th>Matricule</th><th>Nom</th><th>Matière</th></tr></thead><tbody>{teachers.slice(0,10).map(t=><tr key={t.id}><td>{t.matricule}</td><td>{t.last_name} {t.first_name}</td><td>{t.subject||"—"}</td></tr>)}</tbody></table>:<p className="empty">Aucun enseignant enregistré.</p>}</div></div></>
}

function Finance({profile}:any){
 const [payments,setPayments]=useState<any[]>([]),[students,setStudents]=useState<Student[]>([]);
 async function load(){const [p,s]=await Promise.all([supabase.from("payments").select("*").eq("school_id",profile.school_id).order("paid_at",{ascending:false}),supabase.from("students").select("*").eq("school_id",profile.school_id).order("last_name")]);setPayments(p.data||[]);setStudents(s.data||[])}
 useEffect(()=>{load()},[profile.school_id]);
 const total=payments.reduce((a,p)=>a+Number(p.amount),0);
 async function add(){const s=students[0];if(!s){alert("Ajoutez d'abord un élève.");return}const amount=Number(prompt("Montant en FC","100000"));if(!amount)return;const {error}=await supabase.from("payments").insert({school_id:profile.school_id,student_id:s.id,receipt_number:"REC-"+Date.now().toString().slice(-7),amount,method:"cash",status:"validated",received_by:profile.id});if(error)alert(error.message);else load()}
 return <><div className="head"><div><h1>Finances</h1><p>Encaissements, reçus, frais, impayés et dépenses.</p></div><button className="btn" onClick={add}><Plus size={17}/> Encaisser</button></div><div className="cards"><Stat title="Total encaissé" value={money(total)} icon={<Wallet/>}/><Stat title="Transactions" value={payments.length} icon={<BookOpen/>}/><Stat title="Impayés" value="—" icon={<ShieldCheck/>}/><Stat title="Devise" value="FC" icon={<Wallet/>}/></div><div className="panel"><h3>Derniers paiements</h3><div className="tableWrap"><table><thead><tr><th>Reçu</th><th>Élève</th><th>Montant</th><th>Mode</th><th>Date</th></tr></thead><tbody>{payments.map(p=>{const s=students.find(x=>x.id===p.student_id);return <tr key={p.id}><td>{p.receipt_number}</td><td>{s?s.last_name+" "+s.first_name:"—"}</td><td><b>{money(Number(p.amount))}</b></td><td>{p.method}</td><td>{new Date(p.paid_at).toLocaleDateString("fr-FR")}</td></tr>})}{!payments.length&&<tr><td colSpan={5} className="empty">Aucun encaissement.</td></tr>}</tbody></table></div></div></>
}

function Staff({profile}:any){const [rows,setRows]=useState<Teacher[]>([]);useEffect(()=>{supabase.from("teachers").select("*").eq("school_id",profile.school_id).order("last_name").then(({data})=>setRows(data||[]))},[profile.school_id]);return <><div className="head"><div><h1>Personnel</h1><p>Enseignants et personnel autorisé.</p></div></div><div className="panel"><h3>Enseignants</h3><table><thead><tr><th>Matricule</th><th>Nom</th><th>Téléphone</th><th>Matière</th><th>Statut</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.matricule}</td><td>{t.last_name} {t.first_name}</td><td>{t.phone||"—"}</td><td>{t.subject||"—"}</td><td><span className="badge">{t.active?"Actif":"Inactif"}</span></td></tr>)}</tbody></table></div></>}

function SettingsPage({school,profile,reload}:any){
 const [name,setName]=useState(school?.name||""),[phone,setPhone]=useState(school?.phone||""),[email,setEmail]=useState(school?.email||""),[address,setAddress]=useState(school?.address||""),[saving,setSaving]=useState(false);
 async function save(){setSaving(true);const {error}=await supabase.from("schools").update({name,phone,email,address,updated_at:new Date().toISOString()}).eq("id",profile.school_id);if(error)alert(error.message);else{alert("Paramètres enregistrés.");reload()}setSaving(false)}
 return <><div className="head"><div><h1>Paramètres</h1><p>Nom, logo, identité et coordonnées modifiables sans coder.</p></div></div><div className="panel formGrid"><label>Nom de l'école<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Téléphone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Adresse<input value={address} onChange={e=>setAddress(e.target.value)}/></label><div><button className="btn" disabled={saving} onClick={save}>{saving?"Enregistrement…":"Enregistrer"}</button></div></div></>
}