"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {schoolSupabase as supabase} from "../lib/supabase";
import {Boxes,Building2,ClipboardList,Truck, Wrench,ScanSearch,ArrowLeftRight,FileDown,Plus,RefreshCw,Search,ShieldCheck} from "lucide-react";

type Profile={id:string;school_id:string;full_name:string|null;permission_overrides?:Record<string,boolean>;roles?:{name:string;label:string}|null};
type ModuleKey="assets"|"requests"|"suppliers"|"purchases"|"maintenance"|"audits"|"locations"|"transfers";
const modules:{key:ModuleKey;label:string;table:string;icon:any;columns:string[];title:string}[]=[
 {key:"assets",label:"Équipements",table:"inventory_assets",icon:Building2,columns:["asset_code","name","category","brand","serial_number","status","condition_status"],title:"Équipements et immobilisations"},
 {key:"requests",label:"Demandes",table:"inventory_requests",icon:ClipboardList,columns:["request_number","department","purpose","needed_by","status"],title:"Demandes de matériel"},
 {key:"suppliers",label:"Fournisseurs",table:"inventory_suppliers",icon:Truck,columns:["name","contact_name","phone","email","active"],title:"Achats et fournisseurs"},
 {key:"purchases",label:"Achats",table:"inventory_purchase_orders",icon:Boxes,columns:["order_number","supplier_name","order_date","expected_date","subtotal","currency","status"],title:"Bons de commande"},
 {key:"maintenance",label:"Maintenance",table:"inventory_maintenance",icon:Wrench,columns:["ticket_number","title","priority","status","assigned_to","due_date"],title:"Maintenance et réparations"},
 {key:"audits",label:"Inventaire physique",table:"inventory_audits",icon:ScanSearch,columns:["audit_number","title","scheduled_date","status","notes"],title:"Inventaire physique"},
 {key:"locations",label:"Magasins et emplacements",table:"inventory_locations",icon:Building2,columns:["name","location_code","description","active"],title:"Magasins et emplacements"},
 {key:"transfers",label:"Transferts",table:"inventory_transfers",icon:ArrowLeftRight,columns:["transfer_number","quantity","status","reason","created_at"],title:"Transferts de matériel"}
];
const labels:Record<string,string>={asset_code:"Code",name:"Nom",category:"Catégorie",brand:"Marque",serial_number:"N° série",status:"Statut",condition_status:"État",request_number:"N° demande",department:"Service",purpose:"Motif",needed_by:"Souhaité le",contact_name:"Contact",phone:"Téléphone",email:"E-mail",active:"Actif",order_number:"N° commande",supplier_name:"Fournisseur",order_date:"Date",expected_date:"Livraison prévue",subtotal:"Total",currency:"Devise",ticket_number:"N° ticket",title:"Objet",priority:"Priorité",assigned_to:"Responsable",due_date:"Échéance",audit_number:"N° inventaire",scheduled_date:"Date prévue",notes:"Notes",location_code:"Code emplacement",description:"Description",quantity:"Quantité",reason:"Motif",created_at:"Créé le"};
const inputStyle:React.CSSProperties={width:"100%",padding:"10px 12px",border:"1px solid #dbe3ed",borderRadius:10,background:"#fff",color:"#152b40",fontSize:14};
const cardStyle:React.CSSProperties={background:"#fff",border:"1px solid #e4eaf1",borderRadius:16,padding:16};
export default function LogisticsConsole({profile,can}:{profile:Profile;can:(feature:string,...roles:string[])=>boolean}){
 const [active,setActive]=useState<ModuleKey>("assets"),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<Record<string,string>>({});
 const editable=can("inventory_logistics","promoteur","administrateur","logisticien")||can("inventory","promoteur","administrateur","logisticien");
 const current=modules.find(m=>m.key===active)!;
 const load=useCallback(async()=>{setLoading(true);setError("");const {data,error}=await supabase.from(current.table).select("*").eq("school_id",profile.school_id).order("created_at",{ascending:false}).limit(200);if(error)setError(error.message);setRows(data||[]);setLoading(false)},[current,profile.school_id]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 function begin(){setForm({});setShowForm(true);setNotice("");setError("")}
 async function save(e:React.FormEvent){e.preventDefault();if(!editable)return;setSaving(true);setError("");setNotice("");const base:any={school_id:profile.school_id};Object.entries(form).forEach(([k,v])=>{if(v!=="")base[k]=v});
 if(active==="assets"){if(!base.asset_code||!base.name){setError("Le code et le nom de l’équipement sont obligatoires.");setSaving(false);return}base.created_by=profile.id}
 if(active==="requests"){if(!base.request_number||!base.purpose){setError("Le numéro et le motif de la demande sont obligatoires.");setSaving(false);return}base.requester_id=profile.id}
 if(active==="suppliers"&&!base.name){setError("Le nom du fournisseur est obligatoire.");setSaving(false);return}
 if(active==="purchases"){if(!base.order_number||!base.supplier_name){setError("Le numéro de commande et le fournisseur sont obligatoires.");setSaving(false);return}base.created_by=profile.id}
 if(active==="maintenance"){if(!base.ticket_number||!base.title){setError("Le numéro du ticket et son objet sont obligatoires.");setSaving(false);return}base.reported_by=profile.id}
 if(active==="audits"){if(!base.audit_number||!base.title){setError("Le numéro et le titre de l’inventaire sont obligatoires.");setSaving(false);return}base.created_by=profile.id}
 const {error}=await supabase.from(current.table).insert(base);if(error)setError(error.message);else{setNotice("Enregistrement créé.");setShowForm(false);await load()}setSaving(false)}
 function exportCsv(){const csv=[current.columns.map(c=>labels[c]||c).join(";"),...filtered.map(row=>current.columns.map(c=>String(row[c]??"").replace(/;/g,",").replace(/\r?\n/g," ")).join(";"))].join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="monatshiebe-"+active+".csv";a.click();URL.revokeObjectURL(url)}
 const formFields:Record<ModuleKey,{key:string;label:string;type?:string;required?:boolean;options?:string[]}[]>={assets:[{key:"asset_code",label:"Code inventaire",required:true},{key:"name",label:"Nom de l’équipement",required:true},{key:"category",label:"Catégorie"},{key:"brand",label:"Marque"},{key:"model",label:"Modèle"},{key:"serial_number",label:"Numéro de série"},{key:"purchase_date",label:"Date d’achat",type:"date"},{key:"warranty_until",label:"Fin de garantie",type:"date"},{key:"acquisition_cost",label:"Coût d’acquisition",type:"number"},{key:"currency",label:"Devise",options:["FC","USD"]},{key:"status",label:"Statut",options:["active","assigned","maintenance","damaged","retired","lost"]},{key:"condition_status",label:"État",options:["good","worn","damaged","out_of_service"]},{key:"notes",label:"Notes"}],
 requests:[{key:"request_number",label:"Numéro de demande",required:true},{key:"department",label:"Service demandeur"},{key:"needed_by",label:"Date souhaitée",type:"date"},{key:"purpose",label:"Motif / justification",required:true},{key:"decision_note",label:"Commentaire"}],
 suppliers:[{key:"name",label:"Nom du fournisseur",required:true},{key:"contact_name",label:"Personne de contact"},{key:"phone",label:"Téléphone"},{key:"email",label:"E-mail",type:"email"},{key:"address",label:"Adresse"},{key:"tax_number",label:"N° fiscal"},{key:"notes",label:"Notes"}],
 purchases:[{key:"order_number",label:"Numéro de commande",required:true},{key:"supplier_name",label:"Fournisseur",required:true},{key:"order_date",label:"Date de commande",type:"date"},{key:"expected_date",label:"Livraison prévue",type:"date"},{key:"subtotal",label:"Montant total",type:"number"},{key:"currency",label:"Devise",options:["FC","USD"]},{key:"invoice_reference",label:"Référence facture"},{key:"notes",label:"Notes"}],
 maintenance:[{key:"ticket_number",label:"Numéro de ticket",required:true},{key:"title",label:"Objet du problème",required:true},{key:"description",label:"Description"},{key:"priority",label:"Priorité",options:["low","normal","high","urgent"]},{key:"assigned_to",label:"Technicien / prestataire"},{key:"due_date",label:"Échéance",type:"date"},{key:"estimated_cost",label:"Coût estimé",type:"number"},{key:"resolution_notes",label:"Notes de résolution"}],
 audits:[{key:"audit_number",label:"Numéro d’inventaire",required:true},{key:"title",label:"Titre de l’opération",required:true},{key:"scheduled_date",label:"Date prévue",type:"date"},{key:"notes",label:"Notes"}],
 locations:[{key:"name",label:"Nom du magasin / emplacement",required:true},{key:"location_code",label:"Code emplacement"},{key:"description",label:"Description"}],
 transfers:[{key:"transfer_number",label:"Numéro de transfert",required:true},{key:"quantity",label:"Quantité",type:"number"},{key:"reason",label:"Motif"},{key:"status",label:"Statut",options:["pending","approved","completed","rejected"]}]
 };
 const stats=useMemo(()=>({total:rows.length,pending:rows.filter(r=>["pending","draft","reported","in_progress"].includes(r.status)).length}),[rows]);
 return <div style={{display:"grid",gap:18,color:"#172b43"}}>
  <div style={{...cardStyle,background:"linear-gradient(120deg,#102f4e,#185a75)",color:"#fff",border:0,padding:22}}><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{background:"#ffffff20",borderRadius:14,padding:12}}><Boxes size={28}/></div><div><div style={{fontSize:12,letterSpacing:1.5,opacity:.8}}>MONATSHIEBE LOGICIEL</div><h2 style={{margin:"4px 0",fontSize:24}}>Centre logistique</h2><div style={{opacity:.82,fontSize:14}}>Stocks, matériel, achats et suivi des immobilisations</div></div></div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:18}}><div style={{background:"#ffffff18",borderRadius:12,padding:"10px 14px"}}><div style={{fontSize:12,opacity:.8}}>Enregistrements affichés</div><b style={{fontSize:20}}>{stats.total}</b></div><div style={{background:"#ffffff18",borderRadius:12,padding:"10px 14px"}}><div style={{fontSize:12,opacity:.8}}>À traiter / en cours</div><b style={{fontSize:20}}>{stats.pending}</b></div><div style={{background:"#ffffff18",borderRadius:12,padding:"10px 14px"}}><div style={{fontSize:12,opacity:.8}}>Accès</div><b style={{fontSize:14}}>{editable?"Gestion autorisée":"Consultation"}</b></div></div></div>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{modules.map(m=>{const Icon=m.icon;return <button key={m.key} onClick={()=>{setActive(m.key);setShowForm(false);setQuery("")}} style={{display:"flex",alignItems:"center",gap:7,padding:"10px 12px",borderRadius:11,border:active===m.key?"1px solid #174e72":"1px solid #e1e7ef",background:active===m.key?"#eaf3f8":"#fff",color:active===m.key?"#123c5c":"#526276",fontWeight:600,cursor:"pointer"}}><Icon size={16}/>{m.label}</button>})}</div>
  <section style={cardStyle}><div style={{display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap"}}><div><h3 style={{margin:"0 0 5px",fontSize:19}}>{current.title}</h3><p style={{margin:0,color:"#718096",fontSize:13}}>Données limitées à l’établissement connecté. {active==="requests"?"Les demandes doivent être approuvées avant délivrance.":active==="audits"?"Les lignes de comptage sont conservées dans le module d’inventaire physique.":""}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>void load()} style={{...buttonStyle,background:"#f5f8fb",color:"#34516b"}}><RefreshCw size={15}/> Actualiser</button><button onClick={exportCsv} style={{...buttonStyle,background:"#edf7f1",color:"#226444"}}><FileDown size={15}/> Export CSV</button>{editable&&<button onClick={begin} style={{...buttonStyle,background:"#123e5d",color:"#fff"}}><Plus size={15}/> Nouveau</button>}</div></div>
  <div style={{position:"relative",margin:"16px 0"}}><Search size={16} style={{position:"absolute",left:12,top:12,color:"#8091a5"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans les enregistrements…" style={{...inputStyle,paddingLeft:36}}/></div>
  {error&&<div role="alert" style={{padding:12,marginBottom:12,borderRadius:10,background:"#fff0f0",color:"#9b2525",fontSize:13}}>{error}</div>}{notice&&<div style={{padding:12,marginBottom:12,borderRadius:10,background:"#eef9f0",color:"#226444",fontSize:13}}>{notice}</div>}
  {showForm&&<form onSubmit={save} style={{padding:16,marginBottom:18,border:"1px solid #dce7f0",borderRadius:13,background:"#f8fbfd"}}><h4 style={{margin:"0 0 12px"}}>Nouvel enregistrement</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{formFields[active].map(field=><label key={field.key} style={{display:"grid",gap:6,fontSize:13,fontWeight:600,color:"#3b4d61"}}>{field.label}{field.options?<select required={field.required} value={form[field.key]||""} onChange={e=>setForm({...form,[field.key]:e.target.value})} style={inputStyle}><option value="">Sélectionner…</option>{field.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input required={field.required} type={field.type||"text"} value={form[field.key]||""} onChange={e=>setForm({...form,[field.key]:e.target.value})} style={inputStyle}/>}</label>)}</div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:14}}><button type="button" onClick={()=>setShowForm(false)} style={{...buttonStyle,background:"#e9eef4",color:"#40546a"}}>Annuler</button><button disabled={saving} type="submit" style={{...buttonStyle,background:"#123e5d",color:"#fff"}}>{saving?"Enregistrement…":"Enregistrer"}</button></div></form>}
  {loading?<p style={{padding:22,color:"#718096"}}>Chargement des données…</p>:filtered.length===0?<div style={{padding:"34px 12px",textAlign:"center",color:"#77869a"}}><ShieldCheck size={28}/><p style={{marginBottom:4}}>Aucun enregistrement trouvé</p><small>Créez le premier élément ou modifiez votre recherche.</small></div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{current.columns.map(c=><th key={c} style={{textAlign:"left",padding:"11px 10px",borderBottom:"1px solid #e4eaf1",background:"#f7f9fc",color:"#63758a",whiteSpace:"nowrap"}}>{labels[c]||c}</th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={row.id||i}>{current.columns.map(c=><td key={c} style={{padding:"12px 10px",borderBottom:"1px solid #edf1f5",color:"#273d52",maxWidth:240,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{row[c]===true?"Oui":row[c]===false?"Non":row[c]??"—"}</td>)}</tr>)}</tbody></table></div>}
  </section>
  <div style={{display:"flex",gap:8,alignItems:"flex-start",color:"#748397",fontSize:12}}><ShieldCheck size={16}/><span>La base applique les permissions et l’isolation par école. Les demandes, commandes, audits et transferts disposent de statuts de suivi; les documents peuvent être exportés en CSV depuis chaque liste.</span></div>
 </div>
}
const buttonStyle:React.CSSProperties={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:7,padding:"10px 12px",border:"0",borderRadius:10,fontWeight:600,fontSize:13,cursor:"pointer"};
