"use client";
import {useEffect,useState} from "react";
import {schoolSupabase as supabase} from "../lib/supabase";
import {Bell, Bus, Utensils, BedDouble, Download, Plus, RefreshCw} from "lucide-react";

type Props={profile:any;can:(feature:string,...roles:string[])=>boolean;activeModule:string};
const tabs=[
 {id:"sms_notifications",label:"Notifications aux parents",icon:Bell,table:"parent_notifications"},
 {id:"school_transport",label:"Transport scolaire",icon:Bus,table:"transport_routes"},
 {id:"school_canteen",label:"Cantine scolaire",icon:Utensils,table:"canteen_menu_items"},
 {id:"boarding_dormitory",label:"Internat & dortoirs",icon:BedDouble,table:"dormitories"}
];
const fields:Record<string,{name:string;label:string;type?:string;required?:boolean}[]>={
 parent_notifications:[],
 electronic_payments:[{name:"payment_reference",label:"Référence",required:true},{name:"payer_name",label:"Nom du payeur"},{name:"payer_phone",label:"Téléphone"},{name:"provider",label:"Opérateur (orange_money, mpesa, airtel_money, afrimoney, bank, other)",required:true},{name:"purpose",label:"Motif (frais scolaires, cantine…)"},{name:"amount",label:"Montant",type:"number",required:true},{name:"currency",label:"Devise (CDF ou USD)",required:true}],
 transport_routes:[{name:"name",label:"Nom de la ligne",required:true},{name:"route_code",label:"Code de ligne"},{name:"vehicle_label",label:"Véhicule / plaque"},{name:"driver_name",label:"Nom du chauffeur"},{name:"driver_phone",label:"Téléphone du chauffeur"},{name:"capacity",label:"Capacité",type:"number"},{name:"departure_time",label:"Heure de départ",type:"time"},{name:"return_time",label:"Heure de retour",type:"time"},{name:"monthly_fee",label:"Frais mensuels",type:"number"},{name:"currency",label:"Devise (CDF ou USD)"}],
 canteen_menu_items:[{name:"name",label:"Nom du plat / produit",required:true},{name:"category",label:"Catégorie"},{name:"description",label:"Description"},{name:"price",label:"Prix",type:"number"},{name:"currency",label:"Devise (CDF ou USD)"},{name:"stock_quantity",label:"Stock",type:"number"}],
 dormitories:[{name:"name",label:"Nom du dortoir",required:true},{name:"gender",label:"Genre (male, female, mixed)"},{name:"building",label:"Bâtiment"},{name:"capacity",label:"Capacité",type:"number"},{name:"supervisor_name",label:"Responsable"},{name:"supervisor_phone",label:"Téléphone responsable"}]
};
export default function SchoolOperationsModules({profile,can,activeModule}:Props){
 const [tab,setTab]=useState(tabs.some(t=>t.id===activeModule)?activeModule:tabs[0].id),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[form,setForm]=useState<Record<string,string>>({}),[showForm,setShowForm]=useState(false);
 useEffect(()=>{if(tabs.some(t=>t.id===activeModule))setTab(activeModule)},[activeModule]);
 const active=tabs.find(t=>t.id===tab)||tabs[0];
 async function load(){setLoading(true);const {data,error}=await supabase.from(active.table).select("*").eq("school_id",profile.school_id).order("created_at",{ascending:false}).limit(250);if(error)setNotice(error.message);else{setRows(data||[]);setNotice("")}setLoading(false)}
 useEffect(()=>{load()},[tab,profile.school_id]);
 const permitted=tab!=="sms_notifications"&&can(tab,"promoteur","directeur","administrateur","finance","comptable","rh","secretaire","logisticien","surveillant","gestionnaire");
 function exportCsv(){const values=rows;if(!values.length){setNotice("Aucune donnée à exporter.");return}const keys=Array.from(new Set(values.flatMap(x=>Object.keys(x))));const csv=[keys.join(";"),...values.map(r=>keys.map(k=>String(r[k]??"").replace(/"/g,'""')).map(v=>'"'+v+'"').join(";"))].join("\r\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=active.table+"-"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(url);void supabase.from("school_import_export_logs").insert({school_id:profile.school_id,operation:"export",entity_type:active.table,file_name:a.download,status:"completed",row_count:values.length,performed_by:profile.id})}
 async function save(){if(tab==="sms_notifications")return;const payload:any={school_id:profile.school_id};for(const f of fields[active.table]||[]){const v=form[f.name];if(v!==undefined&&v!=="")payload[f.name]=f.type==="number"?Number(v):v}if(active.table==="transport_routes"||active.table==="canteen_menu_items"||active.table==="dormitories"){if(active.table==="transport_routes"){payload.created_by=profile.id;if(!payload.currency)payload.currency="CDF"}if(active.table==="canteen_menu_items"&&!payload.currency)payload.currency="CDF";if(active.table==="dormitories"&&!payload.capacity)payload.capacity=1}const {error}=await supabase.from(active.table).insert(payload);if(error){setNotice(error.message);return}setForm({});setShowForm(false);setNotice("Enregistrement ajouté.");load()}
 const title=(r:any)=>r.name||r.title||r.payment_reference||r.recipient_name||r.file_name||r.item_name||r.id;
 const subtitle=(r:any)=>r.message||r.description||r.recipient_phone||r.provider||r.status||r.operation||"";
 return <section className="space-y-5"><div><h2 className="text-2xl font-bold">Services scolaires</h2><p className="text-sm opacity-70">Notifications destinées aux parents, transport, cantine et internat.</p></div>
 
 <div className="rounded-2xl border bg-white p-4 text-slate-900 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">{active.label}</h3><p className="text-sm text-slate-500">{rows.length} enregistrement(s) chargé(s)</p></div><div className="flex gap-2"><button onClick={load} className="rounded-lg border px-3 py-2 text-sm"><RefreshCw size={15} className="mr-1 inline"/>Actualiser</button><button onClick={exportCsv} className="rounded-lg border px-3 py-2 text-sm"><Download size={15} className="mr-1 inline"/>Exporter CSV</button>{permitted&&fields[active.table]&&<button onClick={()=>setShowForm(!showForm)} className="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white"><Plus size={15} className="mr-1 inline"/>Ajouter</button>}</div></div>
 {notice&&<p className="my-3 rounded-lg bg-blue-50 p-3 text-sm">{notice}</p>}
 {showForm&&<div className="my-4 grid gap-3 rounded-xl border bg-slate-50 p-4 md:grid-cols-2">{(fields[active.table]||[]).map(f=><label key={f.name} className="text-sm font-medium">{f.label}<input required={f.required} type={f.type||"text"} value={form[f.name]||""} onChange={e=>setForm({...form,[f.name]:e.target.value})} className="mt-1 block w-full rounded-lg border bg-white px-3 py-2 font-normal"/></label>)}<div className="flex gap-2 md:col-span-2"><button onClick={save} className="rounded-lg bg-blue-700 px-4 py-2 text-white">Enregistrer</button><button onClick={()=>setShowForm(false)} className="rounded-lg border px-4 py-2">Annuler</button></div></div>}
 {tab==="sms_notifications"&&<div className="my-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Les notifications sont générées automatiquement lors de l’enregistrement d’un fait disciplinaire et consultables dans l’espace parent de l’élève concerné. Aucune notification téléphonique n’est envoyée.</div>}
 {loading?<p className="py-8 text-center">Chargement…</p>:rows.length===0?<p className="py-8 text-center text-slate-500">Aucun enregistrement pour le moment.</p>:<div className="mt-4 divide-y">{rows.map(r=><div key={r.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate font-semibold">{title(r)}</p><p className="truncate text-sm text-slate-500">{subtitle(r)}</p></div><span className="shrink-0 rounded-full bg-slate-100 px-3 py-1 text-xs">{r.status||r.payment_status||r.row_count||"—"}</span></div>)}</div>}</div></section>
}
