"use client";
import {useCallback,useEffect,useState} from "react";
import {schoolSupabase as supabase} from "../lib/supabase";
import {Plus,RefreshCw,Search,UserRound,Save,Trash2,BriefcaseBusiness,ShieldCheck} from "lucide-react";

const empty={staff_matricule:"",full_name:"",job_title:"",phone:"",email:"",contract_type:"CDI",monthly_salary:"0",salary_currency:"FC",education_level:"",weekly_service_hours:"40",hired_at:"",duties:"",status:"active"};
const input:React.CSSProperties={width:"100%",padding:"10px 11px",border:"1px solid #dbe3ed",borderRadius:9,fontSize:14,background:"#fff",color:"#20374d"};
const btn:React.CSSProperties={border:0,borderRadius:9,padding:"10px 12px",display:"inline-flex",gap:7,alignItems:"center",fontWeight:600,cursor:"pointer"};
export default function StaffRegistry({profile}:{profile:any}){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[query,setQuery]=useState(""),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const role=profile?.roles?.name||"";
 const canManage=["promoteur","directeur","administrateur"].includes(role);
 const load=useCallback(async()=>{setLoading(true);setError("");const {data,error}=await supabase.from("school_staff").select("*").eq("school_id",profile.school_id).order("created_at",{ascending:false}).limit(1000);if(error){setError(error.message);setRows([])}else setRows(data||[]);setLoading(false)},[profile.school_id]);
 useEffect(()=>{void load()},[load]);
 const filtered=rows.filter(r=>([r.staff_matricule,r.full_name,r.job_title,r.phone,r.email,r.contract_type,r.status].join(" ")).toLowerCase().includes(query.toLowerCase()));
 function begin(row?:any){setNotice("");setError("");if(row){setEditing(row.id);setForm({staff_matricule:row.staff_matricule||"",full_name:row.full_name||"",job_title:row.job_title||"",phone:row.phone||"",email:row.email||"",contract_type:row.contract_type||"CDI",monthly_salary:String(row.monthly_salary??0),salary_currency:row.salary_currency||"FC",education_level:row.education_level||"",weekly_service_hours:String(row.weekly_service_hours??40),hired_at:row.hired_at||"",duties:row.duties||"",status:row.status||"active"})}else{setEditing(null);setForm({...empty,staff_matricule:"PERS-"+new Date().getFullYear()+"-"+Math.random().toString(36).slice(2,7).toUpperCase()})}setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!canManage)return;setSaving(true);setError("");setNotice("");const payload:any={school_id:profile.school_id,staff_matricule:form.staff_matricule.trim(),full_name:form.full_name.trim(),job_title:form.job_title.trim(),phone:form.phone.trim()||null,email:form.email.trim()||null,contract_type:form.contract_type,monthly_salary:Number(form.monthly_salary||0),salary_currency:form.salary_currency,education_level:form.education_level.trim()||null,weekly_service_hours:Number(form.weekly_service_hours||0),hired_at:form.hired_at||null,duties:form.duties.trim()||null,status:form.status,updated_at:new Date().toISOString()};let result;if(editing)result=await supabase.from("school_staff").update(payload).eq("id",editing).eq("school_id",profile.school_id);else result=await supabase.from("school_staff").insert({...payload,created_by:profile.id});if(result.error)setError(result.error.message);else{setNotice(editing?"Dossier du personnel mis à jour.":"Personnel engagé et enregistré. Aucun compte de connexion n’a été créé.");setOpen(false);setEditing(null);setForm(empty);await load()}setSaving(false)}
 async function remove(row:any){if(!canManage||!window.confirm("Supprimer le dossier de "+row.full_name+" ? Cette action est définitive."))return;const {error}=await supabase.from("school_staff").delete().eq("id",row.id).eq("school_id",profile.school_id);if(error)setError(error.message);else{setNotice("Dossier supprimé.");await load()}}
 const field=(key:string,label:string,type="text",required=false)=><label key={key} style={{display:"grid",gap:5,fontSize:12,fontWeight:650,color:"#40566b"}}>{label}<input required={required} type={type} value={form[key]??""} onChange={e=>setForm({...form,[key]:e.target.value})} style={input}/></label>;
 return <div style={{display:"grid",gap:16,color:"#1a3045"}}>
  <div style={{padding:22,borderRadius:16,background:"linear-gradient(120deg,#102f4e,#1d6078)",color:"#fff"}}><div style={{fontSize:11,letterSpacing:1.5,opacity:.8}}>MONATSHIEBE LOGICIEL • RESSOURCES HUMAINES</div><h2 style={{fontSize:24,margin:"6px 0"}}>Engagements du personnel</h2><p style={{margin:0,opacity:.88}}>Registre central de tous les travailleurs : enseignants, secrétaires, gardiens, nettoyeurs, jardiniers, prestataires et journaliers. Un dossier peut exister sans compte de connexion.</p></div>
  <section style={{padding:16,background:"#fff",border:"1px solid #e3eaf1",borderRadius:15}}>
   <div style={{display:"flex",gap:10,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap"}}><div><h3 style={{margin:"0 0 4px"}}>Registre des engagements</h3><small style={{color:"#748397"}}>{rows.length} dossier(s) • {rows.filter(x=>x.status==="active").length} actif(s)</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>void load()} style={{...btn,background:"#f0f4f8",color:"#34516b"}}><RefreshCw size={15}/>Actualiser</button>{canManage&&<button onClick={()=>begin()} style={{...btn,background:"#143e5c",color:"#fff"}}><Plus size={15}/>Engager un membre</button>}</div></div>
   <div style={{position:"relative",margin:"15px 0"}}><Search size={15} style={{position:"absolute",left:11,top:12,color:"#8493a5"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher par matricule, nom, poste, téléphone…" style={{...input,paddingLeft:34}}/></div>
   {notice&&<p style={{padding:10,background:"#eef8f1",color:"#256440",borderRadius:8}}>{notice}</p>}{error&&<p role="alert" style={{padding:10,background:"#fff0f0",color:"#9b2727",borderRadius:8}}>{error}</p>}
   {open&&<form onSubmit={save} style={{padding:15,background:"#f7fafc",border:"1px solid #dce6ef",borderRadius:12,marginBottom:16}}><h4 style={{margin:"0 0 12px"}}>{editing?"Modifier le dossier":"Nouveau dossier d’engagement"}</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:11}}>
    {field("staff_matricule","Matricule personnel","text",true)}{field("full_name","Nom complet","text",true)}{field("job_title","Fonction / poste","text",true)}{field("phone","Téléphone")}{field("email","Adresse e-mail","email")}{field("monthly_salary","Salaire mensuel","number",true)}{field("education_level","Niveau d’études")}{field("weekly_service_hours","Heures de service par semaine","number",true)}{field("hired_at","Date d’engagement","date")}
    <label style={{display:"grid",gap:5,fontSize:12,fontWeight:650,color:"#40566b"}}>Type de contrat<select value={form.contract_type} onChange={e=>setForm({...form,contract_type:e.target.value})} style={input}>{["CDI","CDD","Journalier","Prestataire","Stage","Bénévole"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label style={{display:"grid",gap:5,fontSize:12,fontWeight:650,color:"#40566b"}}>Devise du salaire<select value={form.salary_currency} onChange={e=>setForm({...form,salary_currency:e.target.value})} style={input}><option value="FC">FC</option><option value="USD">USD</option></select></label>
    <label style={{display:"grid",gap:5,fontSize:12,fontWeight:650,color:"#40566b"}}>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} style={input}><option value="active">Actif</option><option value="on_leave">En congé</option><option value="suspended">Suspendu</option><option value="departed">Parti</option></select></label>
    <label style={{display:"grid",gap:5,fontSize:12,fontWeight:650,color:"#40566b",gridColumn:"1/-1"}}>Attributions / responsabilités<textarea rows={3} value={form.duties} onChange={e=>setForm({...form,duties:e.target.value})} style={input}/></label>
   </div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:12}}><button type="button" onClick={()=>setOpen(false)} style={{...btn,background:"#e8edf3",color:"#40566b"}}>Annuler</button><button disabled={saving} style={{...btn,background:"#143e5c",color:"#fff"}}><Save size={15}/>{saving?"Enregistrement…":"Enregistrer le dossier"}</button></div></form>}
   {loading?<p style={{padding:24}}>Chargement du registre…</p>:filtered.length===0?<div style={{padding:30,textAlign:"center",color:"#718096"}}><BriefcaseBusiness size={28}/><p>Aucun dossier du personnel trouvé.</p></div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Matricule","Nom & fonction","Niveau d’études","Heures/semaine","Contrat","Salaire mensuel","Engagement","Statut","Accès applicatif","Actions"].map(x=><th key={x} style={{padding:10,textAlign:"left",background:"#f5f8fb",borderBottom:"1px solid #e1e8f0",whiteSpace:"nowrap"}}>{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}><b>{r.staff_matricule}</b></td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}><b>{r.full_name}</b><div style={{color:"#718096",marginTop:3}}>{r.job_title}</div><div style={{color:"#718096"}}>{r.phone||r.email||"—"}</div></td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{r.education_level||"—"}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{r.weekly_service_hours??0} h</td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{r.contract_type}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(Number(r.monthly_salary||0))} {r.salary_currency==="USD"?"$":"FC"}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5",whiteSpace:"nowrap"}}>{r.hired_at||"—"}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{({active:"Actif",on_leave:"En congé",suspended:"Suspendu",departed:"Parti"} as any)[r.status]||r.status}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5"}}>{r.profile_id?<span style={{color:"#256440"}}>Compte lié</span>:<span style={{color:"#718096"}}>Aucun compte</span>}</td><td style={{padding:10,borderBottom:"1px solid #edf1f5",whiteSpace:"nowrap"}}>{canManage?<><button title="Modifier" onClick={()=>begin(r)} style={{...btn,background:"#eef4fa",color:"#234b6c",padding:8}}><UserRound size={14}/>Modifier</button><button title="Supprimer" onClick={()=>void remove(r)} style={{...btn,background:"#fff0f0",color:"#a12c2c",padding:8,marginLeft:5}}><Trash2 size={14}/></button></>:<ShieldCheck size={16} color="#718096"/>}</td></tr>)}</tbody></table></div>}
  </section><p style={{fontSize:12,color:"#748397"}}>Important : l’enregistrement dans ce registre ne crée ni adresse e-mail, ni mot de passe, ni accès au logiciel. La gestion des comptes se fait dans « Accès applicatifs ».</p>
 </div>
}
