"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {schoolSupabase as supabase} from "../lib/supabase";
import {Users,CalendarCheck,Wallet,BookOpen,Footprints,Plus,RefreshCw,Search,FileDown,ShieldCheck} from "lucide-react";

type Profile={id:string;school_id:string;full_name:string|null;roles?:{name:string;label:string}|null;permission_overrides?:Record<string,boolean>};
type Key="student_portal"|"staff_attendance"|"staff_payroll"|"library"|"extracurricular";
const configs:{key:Key;label:string;title:string;table:string;icon:any;columns:string[];fields:{key:string;label:string;type?:string;required?:boolean;options?:string[]}[]}[]=[
{key:"student_portal",label:"Portail élèves",title:"Comptes du portail autonome des élèves",table:"student_portal_accounts",icon:Users,columns:["student_id","user_id","active","created_at"],fields:[{key:"student_id",label:"ID de l’élève",required:true},{key:"user_id",label:"ID du compte Auth (UUID)",required:true},{key:"active",label:"Compte actif",options:["true","false"]}]},
{key:"staff_attendance",label:"Présences & congés",title:"Présences quotidiennes du personnel",table:"staff_attendance",icon:CalendarCheck,columns:["attendance_date","school_staff_id","status","check_in","check_out","note"],fields:[{key:"attendance_date",label:"Date",type:"date",required:true},{key:"school_staff_id",label:"Employé",required:true},{key:"status",label:"Présence",options:["present","late","absent","leave","mission"],required:true},{key:"check_in",label:"Heure d’arrivée",type:"time"},{key:"check_out",label:"Heure de départ",type:"time"},{key:"note",label:"Observation"}]},
{key:"staff_payroll",label:"Salaires & paiements",title:"Paiements individuels du personnel",table:"staff_payroll_items",icon:Wallet,columns:["payment_date","staff_name","net_salary","status","payment_method","note"],fields:[{key:"payment_date",label:"Date du paiement",type:"date",required:true},{key:"school_staff_id",label:"Employé à payer",required:true},{key:"amount_paid",label:"Montant payé",type:"number",required:true},{key:"currency",label:"Devise",options:["FC","USD"],required:true},{key:"note",label:"Observation"}]},
{key:"library",label:"Bibliothèque",title:"Catalogue des livres et ouvrages",table:"library_books",icon:BookOpen,columns:["book_code","title","author","category","copies_total","copies_available","shelf_location","condition_status"],fields:[{key:"book_code",label:"Code livre",required:true},{key:"title",label:"Titre",required:true},{key:"isbn",label:"ISBN"},{key:"author",label:"Auteur"},{key:"publisher",label:"Éditeur"},{key:"category",label:"Catégorie"},{key:"publication_year",label:"Année de publication",type:"number"},{key:"copies_total",label:"Exemplaires",type:"number",required:true},{key:"copies_available",label:"Disponibles",type:"number",required:true},{key:"shelf_location",label:"Rayon / emplacement"},{key:"condition_status",label:"État",options:["good","worn","damaged"]},{key:"notes",label:"Notes"}]},
{key:"extracurricular",label:"Parascolaire",title:"Activités et clubs scolaires",table:"extracurricular_activities",icon:Footprints,columns:["title","activity_type","supervisor_name","location","start_at","end_at","status","budget","currency"],fields:[{key:"title",label:"Nom de l’activité",required:true},{key:"activity_type",label:"Type",options:["club","sport","sortie","culture","concours","autre"]},{key:"description",label:"Description"},{key:"supervisor_name",label:"Responsable"},{key:"location",label:"Lieu"},{key:"start_at",label:"Début",type:"datetime-local"},{key:"end_at",label:"Fin",type:"datetime-local"},{key:"capacity",label:"Capacité",type:"number"},{key:"status",label:"Statut",options:["planned","open","completed","cancelled"]},{key:"budget",label:"Budget",type:"number"},{key:"currency",label:"Devise",options:["FC","USD"]}]}
];
const labels:Record<string,string>={student_id:"Élève (UUID)",user_id:"Compte Auth (UUID)",active:"Actif",created_at:"Créé le",attendance_date:"Date",staff_profile_id:"Profil personnel",school_staff_id:"Employé",teacher_id:"Enseignant",status:"Statut",payment_date:"Date du paiement",staff_name:"Employé payé",net_salary:"Montant payé",check_in:"Arrivée",check_out:"Départ",note:"Observation",period_month:"Période",title:"Titre",currency:"Devise",notes:"Notes",book_code:"Code livre",author:"Auteur",category:"Catégorie",copies_total:"Exemplaires",copies_available:"Disponibles",shelf_location:"Emplacement",condition_status:"État",activity_type:"Type",supervisor_name:"Responsable",location:"Lieu",start_at:"Début",end_at:"Fin",budget:"Budget"};
const btn:React.CSSProperties={border:0,borderRadius:9,padding:"10px 12px",display:"inline-flex",gap:7,alignItems:"center",fontWeight:600,cursor:"pointer"};
const input:React.CSSProperties={width:"100%",padding:"10px",border:"1px solid #dbe3ed",borderRadius:9,fontSize:14,background:"#fff",color:"#20374d"};
export default function StudentStaffModules({profile,can,activeModule}:{profile:Profile;can:(feature:string,...roles:string[])=>boolean;activeModule:string}){
const [active,setActive]=useState<Key>(activeModule as Key),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[q,setQ]=useState(""),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false),[loanRows,setLoanRows]=useState<any[]>([]);
useEffect(()=>{if(configs.some(c=>c.key===activeModule))setActive(activeModule as Key)},[activeModule]);
const cfg=configs.find(c=>c.key===active)!;
const role=profile.roles?.name||"";const editable=role==="promoteur"?active==="staff_payroll":(active==="staff_attendance"?can("staff_attendance","etudes","directeur","administrateur","secretaire"):active==="library"?can("library","bibliothecaire","directeur","administrateur"):can(active,"directeur","administrateur")||can("staff","directeur","administrateur"));
const load=useCallback(async()=>{setLoading(true);setError("");const selectFields=active==="staff_attendance"?"*,school_staff:school_staff_id(full_name,staff_matricule,job_title)":active==="staff_payroll"?"*,school_staff:school_staff_id(full_name,staff_matricule,job_title)":"*";const {data,error}=await supabase.from(cfg.table).select(selectFields).eq("school_id",profile.school_id).order("created_at",{ascending:false}).limit(300);if(error)setError(error.message);setRows(data||[]);if(active==="staff_attendance"||active==="staff_payroll"){const staff=await supabase.from("school_staff").select("id,staff_matricule,full_name,job_title,monthly_salary,salary_currency,status").eq("school_id",profile.school_id).eq("status","active").order("full_name");setStaffRows(staff.data||[])}if(active==="library"){const {data:loans}=await supabase.from("library_loans").select("*").eq("school_id",profile.school_id).order("created_at",{ascending:false}).limit(200);setLoanRows(loans||[])}setLoading(false)},[cfg,profile.school_id,active]);
useEffect(()=>{void load()},[load]);
const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
async function save(e:React.FormEvent){e.preventDefault();if(!editable)return;setSaving(true);setError("");setNotice("");const payload:any={school_id:profile.school_id};for(const [k,v] of Object.entries(form)){if(v!==""){if(k==="active")payload[k]=v==="true";else if(["copies_total","copies_available","publication_year","capacity","budget"].includes(k))payload[k]=Number(v);else payload[k]=v}}
if(active==="student_portal"){payload.student_id=payload.student_id?.trim();payload.user_id=payload.user_id?.trim()}
if(active==="staff_attendance"){const emp=staffRows.find((x:any)=>x.id===form.school_staff_id);payload.school_staff_id=form.school_staff_id;payload.staff_profile_id=null;payload.teacher_id=null;payload.recorded_by=profile.id;if(!emp){setError("Sélectionnez un employé enregistré dans le registre du personnel.");setSaving(false);return}}
if(active==="staff_payroll"){const emp=staffRows.find((x:any)=>x.id===form.school_staff_id);if(!emp){setError("Sélectionnez un employé actif du registre.");setSaving(false);return}const amount=Number(form.amount_paid||0);if(amount<=0){setError("Le montant payé doit être supérieur à zéro.");setSaving(false);return}const date=form.payment_date;const month=date.slice(0,7)+"-01";const currency=form.currency;let run=await supabase.from("staff_payroll_runs").select("id").eq("school_id",profile.school_id).eq("period_month",month).eq("currency",currency).maybeSingle();if(!run.data){const made=await supabase.from("staff_payroll_runs").insert({school_id:profile.school_id,period_month:month,title:"Paiements du personnel — "+month,status:"partially_paid",currency,notes:"Paiement individuel enregistré depuis le panneau du promoteur",created_by:profile.id}).select("id").single();if(made.error){setError(made.error.message);setSaving(false);return}run={data:made.data,error:null} as any}const paid=await supabase.from("staff_payroll_items").insert({school_id:profile.school_id,payroll_run_id:run.data.id,school_staff_id:emp.id,staff_name:emp.full_name,base_salary:Number(emp.monthly_salary||0),bonuses:0,deductions:Math.max(0,Number(emp.monthly_salary||0)-amount),net_salary:amount,status:"paid",payment_date:date,payment_method:"cash",note:form.note||null});if(paid.error)setError(paid.error.message);else{setNotice("Paiement enregistré pour "+emp.full_name+".");setFormOpen(false);setForm({});await load()}setSaving(false);return}
if(active==="extracurricular")payload.created_by=profile.id;
const {error}=await supabase.from(cfg.table).insert(payload);if(error)setError(error.message);else{setNotice("Enregistrement créé.");setFormOpen(false);setForm({});await load()}setSaving(false)}
function exportCsv(){const csv=[cfg.columns.map(c=>labels[c]||c).join(";"),...filtered.map(r=>cfg.columns.map(c=>String(r[c]??"").replace(/;/g,",")).join(";"))].join("\n");const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="monatshiebe-"+active+".csv";a.click();URL.revokeObjectURL(url)}
return <div style={{display:"grid",gap:16,color:"#1a3045"}}>
<div style={{padding:22,borderRadius:16,background:"linear-gradient(120deg,#102f4e,#1d6078)",color:"#fff"}}><div style={{fontSize:11,letterSpacing:1.5,opacity:.8}}>MONATSHIEBE LOGICIEL</div><h2 style={{fontSize:24,margin:"6px 0"}}>Vie scolaire et personnel</h2><p style={{margin:0,opacity:.85}}>Portail élèves, gestion du personnel, bibliothèque et activités parascolaires.</p></div>

<section style={{padding:16,background:"#fff",border:"1px solid #e3eaf1",borderRadius:15}}>
<div style={{display:"flex",gap:10,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap"}}><div><h3 style={{margin:"0 0 4px"}}>{cfg.title}</h3><small style={{color:"#748397"}}>Les données sont limitées à l’établissement connecté.</small></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button onClick={()=>void load()} style={{...btn,background:"#f0f4f8",color:"#34516b"}}><RefreshCw size={15}/>Actualiser</button><button onClick={exportCsv} style={{...btn,background:"#eef8f1",color:"#256440"}}><FileDown size={15}/>CSV</button>{editable&&<button onClick={()=>{setForm({});setFormOpen(true)}} style={{...btn,background:"#143e5c",color:"#fff"}}><Plus size={15}/>Nouveau</button>}</div></div>
<div style={{position:"relative",margin:"15px 0"}}><Search size={15} style={{position:"absolute",left:11,top:12,color:"#8493a5"}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher…" style={{...input,paddingLeft:34}}/></div>
{error&&<p role="alert" style={{padding:10,background:"#fff0f0",color:"#9b2727",borderRadius:8}}>{error}</p>}{notice&&<p style={{padding:10,background:"#eef8f1",color:"#256440",borderRadius:8}}>{notice}</p>}
{formOpen&&<form onSubmit={save} style={{padding:14,background:"#f7fafc",border:"1px solid #dce6ef",borderRadius:12,marginBottom:16}}><h4 style={{margin:"0 0 12px"}}>Nouvel enregistrement</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:11}}>{cfg.fields.map(f=><label key={f.key} style={{display:"grid",gap:5,fontSize:12,fontWeight:600,color:"#44576a"}}>{f.label}{f.key==="school_staff_id"?<select required value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})} style={input}><option value="">Choisir un employé…</option>{staffRows.map((s:any)=><option key={s.id} value={s.id}>{s.staff_matricule} — {s.full_name} ({s.job_title})</option>)}</select>:f.options?<select required={f.required} value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})} style={input}><option value="">Sélectionner…</option>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input required={f.required} type={f.type||"text"} value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})} style={input}/>}</label>)}</div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:12}}><button type="button" onClick={()=>setFormOpen(false)} style={{...btn,background:"#e8edf3",color:"#40566b"}}>Annuler</button><button disabled={saving} style={{...btn,background:"#143e5c",color:"#fff"}}>{saving?"Enregistrement…":"Enregistrer"}</button></div></form>}
{loading?<p>Chargement…</p>:filtered.length===0?<div style={{padding:28,textAlign:"center",color:"#718096"}}><ShieldCheck size={26}/><p>Aucun enregistrement.</p></div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{cfg.columns.map(c=><th key={c} style={{padding:10,textAlign:"left",background:"#f5f8fb",borderBottom:"1px solid #e1e8f0",whiteSpace:"nowrap"}}>{labels[c]||c}</th>)}</tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id||i}>{cfg.columns.map(c=><td key={c} style={{padding:10,borderBottom:"1px solid #edf1f5",whiteSpace:"nowrap",maxWidth:240,overflow:"hidden",textOverflow:"ellipsis"}}>{c==="school_staff_id"?(r.school_staff?.full_name||staffRows.find((s:any)=>s.id===r.school_staff_id)?.full_name||"Employé non lié"):c==="net_salary"?new Intl.NumberFormat("fr-FR").format(Number(r[c]||0))+" "+(r.currency||""):r[c]===true?"Oui":r[c]===false?"Non":r[c]??"—"}</td>)}</tr>)}</tbody></table></div>}
{active==="library"&&<div style={{marginTop:22}}><h4>Prêts et retours</h4><p style={{fontSize:12,color:"#748397"}}>Historique des emprunts. La gestion de la disponibilité est conservée dans les tables d’emprunt.</p><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Emprunteur","Type","Prêt le","Retour prévu","Statut"].map(x=><th key={x} style={{textAlign:"left",padding:9,background:"#f5f8fb"}}>{x}</th>)}</tr></thead><tbody>{loanRows.map(r=><tr key={r.id}>{[r.borrower_name,r.borrower_type,r.loan_date,r.due_date,r.status].map((x:any,i)=><td key={i} style={{padding:9,borderBottom:"1px solid #edf1f5"}}>{x||"—"}</td>)}</tr>)}</tbody></table></div></div>}
</section><p style={{fontSize:12,color:"#748397",display:"flex",gap:8}}><ShieldCheck size={15}/>Les accès sont filtrés par établissement et les écritures protégées par les règles de sécurité de la base.</p></div>
}
