"use client";

import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import {ShieldCheck,ArrowLeft} from "lucide-react";
import Link from "next/link";
import "../../../app/globals.css";

export default function PlatformLogin(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(async ({data})=>{if(data.user){const {data:a}=await supabase.from("platform_admins").select("user_id").eq("user_id",data.user.id).eq("active",true).maybeSingle();if(a)location.href="/platform"}})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const {error:e1}=await supabase.auth.signInWithPassword({email,password});if(e1){setError("Email ou mot de passe incorrect.");setBusy(false);return}const {data:u}=await supabase.auth.getUser();const {data:a}=await supabase.from("platform_admins").select("user_id").eq("user_id",u.user?.id||"").eq("active",true).maybeSingle();if(!a){await supabase.auth.signOut();setError("Ce compte n'est pas autorisé à administrer la plateforme.");setBusy(false);return}location.href="/platform"} async function resetPassword(){setError("");if(!email){setError("Entrez d'abord votre email Super Administrateur.");return}const {error:e}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/platform/reset-password"});if(e)setError(e.message);else setError("Un lien de réinitialisation vient d'être envoyé à cette adresse si elle correspond à un compte.");}
 return <main className="authPage"><div className="authCard"><div className="authIcon"><ShieldCheck size={38}/></div><div className="authBrand"><span>PLATEFORME SAAS</span><h1>Administration des écoles</h1><p>Connexion Super Administrateur</p></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="superadmin@..." required/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" minLength={8} required/></label>{error&&<div className="authError">{error}</div>}<button className="authButton" disabled={busy}>{busy?"Connexion…":"Se connecter à la plateforme"}</button><button type="button" className="resetButton" onClick={resetPassword}>Mot de passe oublié / définir mon mot de passe</button></form><Link className="backLink" href="/"><ArrowLeft size={16}/> Retour à la connexion de l'école</Link><p className="authNote">Accès réservé au Super Administrateur. Les comptes des écoles ne peuvent pas accéder à cette interface.</p></div></main>
}