drop policy if exists inventory_items_insert_authorized on public.inventory_items;
create policy inventory_items_insert_authorized on public.inventory_items for insert to authenticated with check (school_id=public.my_school_id() and exists(select 1 from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.school_id=public.my_school_id() and p.active=true and (r.name in ('promoteur','administrateur','logisticien') or coalesce((p.permission_overrides->>'inventory')::boolean,false))));
drop policy if exists inventory_items_update_authorized on public.inventory_items;
create policy inventory_items_update_authorized on public.inventory_items for update to authenticated using (school_id=public.my_school_id() and exists(select 1 from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.school_id=public.my_school_id() and p.active=true and (r.name in ('promoteur','administrateur','logisticien') or coalesce((p.permission_overrides->>'inventory')::boolean,false)))) with check (school_id=public.my_school_id() and exists(select 1 from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.school_id=public.my_school_id() and p.active=true and (r.name in ('promoteur','administrateur','logisticien') or coalesce((p.permission_overrides->>'inventory')::boolean,false))));
drop policy if exists inventory_items_delete_authorized on public.inventory_items;
create policy inventory_items_delete_authorized on public.inventory_items for delete to authenticated using (school_id=public.my_school_id() and exists(select 1 from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.school_id=public.my_school_id() and p.active=true and (r.name in ('promoteur','administrateur','logisticien') or coalesce((p.permission_overrides->>'inventory')::boolean,false))));
drop policy if exists inventory_movements_insert_authorized on public.inventory_movements;
create policy inventory_movements_insert_authorized on public.inventory_movements for insert to authenticated with check (school_id=public.my_school_id() and exists(select 1 from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.school_id=public.my_school_id() and p.active=true and (r.name in ('promoteur','administrateur','logisticien') or coalesce((p.permission_overrides->>'inventory')::boolean,false))) and exists(select 1 from public.inventory_items i where i.id=item_id and i.school_id=public.my_school_id()));
update public.school_modules set enabled=true,updated_at=now() where module_key='inventory';
